

## 🧹 Data Cleaning & Preprocessing

---

### 🎯 Objective:
Learn how to clean, preprocess, and prepare data before applying Machine Learning models.

---

### ⚠️ Why this matters?
Garbage Data ❌ → Garbage Output ❌  
Clean Data ✅ → Better Models ✅

## 🔹 What is Data Cleaning?

Data Cleaning is the process of:
- Fixing incorrect data
- Handling missing values
- Removing duplicates
- Standardizing formats

---

## 🔹 Why is Data Preprocessing Important?

Machine Learning models:
- Cannot handle missing or messy data properly
- Require numerical and consistent input

---

## 🔹 Example of Messy Data:

| Name | Age | City     |
|------|-----|----------|
| Ram  | 25  | Mumbai   |
| Shyam| NaN | mumbai   |
| Ram  | 25  | Mumbai   |

Problems:
- Missing values
- Inconsistent text
- Duplicate rows

In [2]:
import pandas as pd
import numpy as np

In [3]:
from google.colab import files

uploaded = files.upload()

Saving student_data_raw.csv to student_data_raw.csv

In [4]:
df = pd.read_csv("student_data_raw.csv")

Inspecting the dataset

In [5]:
df.head()

,Student_ID,Name,Age,Gender,Course,City,CGPA,Maths,Programming,Communication,Date
0,1,Aarav Sharma,20.0,Male,BE IT,Pune,8.2,82,76.0,88.0,2026-01-15
1,2,Priya Patil,21.0,Female,BE IT,Mumbai,9.1,91,89.0,94.0,2026-01-16
2,3,Rohan Kulkarni,20.0,male,BE IT,pune,7.4,74,68.0,72.0,2026-01-17
3,4,Sneha Joshi,22.0,Female,BE IT,Nashik,8.7,86,92.0,85.0,2026-01-18
4,5,Aditya Deshmukh,21.0,Male,BE IT,pune,NaN,65,71.0,69.0,2026-01-19

In [6]:
df.tail()

,Student_ID,Name,Age,Gender,Course,City,CGPA,Maths,Programming,Communication,Date
28,29,Devendra Patil,21.0,Male,BE IT,Nagpur,6.6,63,150.0,67.0,2026-02-13
29,30,Mansi Khatri,22.0,Female,BE IT,Mumbai,8.0,79,82.0,81.0,2026-02-14
30,7,Kunal Shah,23.0,Male,BE IT,Mumbai,7.1,70,66.0,74.0,2026-01-21
31,18,Pooja Gaikwad,22.0,Female,BE IT,Pune,8.1,80,78.0,83.0,2026-02-02
32,24,Nikita Salunkhe,22.0,Female,BE IT,Mumbai,8.4,83,85.0,87.0,2026-02-08

In [28]:
#Find number of rows and columns

df.shape

(30, 11)

In [8]:
#Find data types

df.dtypes

Student_ID         int64
Name              object
Age              float64
Gender            object
Course            object
City              object
CGPA             float64
Maths              int64
Programming      float64
Communication    float64
Date              object
dtype: object

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Student_ID     33 non-null     int64
 1   Name           33 non-null     object
 2   Age            32 non-null     float64
 3   Gender         32 non-null     object
 4   Course         33 non-null     object
 5   City           32 non-null     object
 6   CGPA           32 non-null     float64
 7   Maths          33 non-null     int64
 8   Programming    32 non-null     float64
 9   Communication  32 non-null     float64
 10  Date           33 non-null     object
dtypes: float64(4), int64(2), object(5)
memory usage: 3.0+ KB

In [10]:
#Identify missing values

df.isnull().sum()

Student_ID       0
Name             0
Age              1
Gender           1
Course           0
City             1
CGPA             1
Maths            0
Programming      1
Communication    1
Date             0
dtype: int64

In [11]:
#View the actual rows containing missing values

df[df.isnull().any(axis=1)]

,Student_ID,Name,Age,Gender,Course,City,CGPA,Maths,Programming,Communication,Date
4,5,Aditya Deshmukh,21.0,Male,BE IT,pune,NaN,65,71.0,69.0,2026-01-19
9,10,Ananya Singh,20.0,Female,BE IT,NaN,8.9,88,91.0,90.0,2026-01-24
14,15,Omkar Shinde,22.0,NaN,BE IT,Nagpur,6.9,67,70.0,65.0,2026-01-29
19,20,Sakshi Thorat,21.0,Female,BE IT,Mumbai,9.0,92,NaN,91.0,2026-02-04
24,25,Yash Joshi,NaN,Male,BE IT,Nashik,7.2,71,74.0,69.0,2026-02-09
27,28,Shreya Gokhale,20.0,Female,BE IT,Pune,8.7,87,89.0,NaN,2026-02-12

In [13]:
#Convert Date column to datetime

df["Date"] = pd.to_datetime(df["Date"])

In [14]:
df.dtypes

Student_ID                int64
Name                     object
Age                     float64
Gender                   object
Course                   object
City                     object
CGPA                    float64
Maths                     int64
Programming             float64
Communication           float64
Date             datetime64[ns]
dtype: object

In [15]:
df["Date"].head()

0   2026-01-15
1   2026-01-16
2   2026-01-17
3   2026-01-18
4   2026-01-19
Name: Date, dtype: datetime64[ns]

Fix text inconsistencies

In [17]:
df["Gender"] = df["Gender"].str.strip().str.title()
df["City"] = df["City"].str.strip().str.title()

In [19]:
#Fill numerical missing values with mean

df["Age"] = df["Age"].fillna(df["Age"].mean())
df["CGPA"] = df["CGPA"].fillna(df["CGPA"].mean())
df["Programming"] = df["Programming"].fillna(df["Programming"].mean())
df["Communication"] = df["Communication"].fillna(df["Communication"].mean())

In [20]:
df.head()

,Student_ID,Name,Age,Gender,Course,City,CGPA,Maths,Programming,Communication,Date
0,1,Aarav Sharma,20.0,Male,BE IT,Pune,8.200000,82,76.0,88.0,2026-01-15
1,2,Priya Patil,21.0,Female,BE IT,Mumbai,9.100000,91,89.0,94.0,2026-01-16
2,3,Rohan Kulkarni,20.0,Male,BE IT,Pune,7.400000,74,68.0,72.0,2026-01-17
3,4,Sneha Joshi,22.0,Female,BE IT,Nashik,8.700000,86,92.0,85.0,2026-01-18
4,5,Aditya Deshmukh,21.0,Male,BE IT,Pune,7.796875,65,71.0,69.0,2026-01-19

Fill categorical missing values with mode

In [21]:
#Fill categorical missing values with mode

df["Gender"] = df["Gender"].fillna(df["Gender"].mode()[0])
df["City"] = df["City"].fillna(df["City"].mode()[0])

In [23]:
df.isnull().sum()

Student_ID       0
Name             0
Age              0
Gender           0
Course           0
City             0
CGPA             0
Maths            0
Programming      0
Communication    0
Date             0
dtype: int64

Remove duplicate rows

In [24]:
df.duplicated().sum()

np.int64(3)

In [25]:
df = df.drop_duplicates()

In [26]:
df.duplicated().sum()

np.int64(0)

In [27]:
df.shape

(30, 11)

Handle outliers

In [31]:
Q1 = df["CGPA"].quantile(0.25)
Q3 = df["CGPA"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print("Lower limit:", lower)
print("Upper limit:", upper)

df[(df["CGPA"] < lower) | (df["CGPA"] > upper)]

Lower limit: 5.112500000000002
Upper limit: 10.812499999999996

,Student_ID,Name,Age,Gender,Course,City,CGPA,Maths,Programming,Communication,Date
18,19,Harsh Vaidya,20.0,Male,BE IT,Nashik,2.1,72,69.0,75.0,2026-02-03

In [33]:
def find_outliers(column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    return df[(df[column] < lower) | (df[column] > upper)]

    find_outliers("Maths")
    find_outliers("Programming")

Handling outliers

In [35]:
df["Maths"] = df["Maths"].clip(0, 100)
df["Programming"] = df["Programming"].clip(0, 100)
df["Communication"] = df["Communication"].clip(0, 100)

df["CGPA"] = df["CGPA"].clip(0, 10)

In [37]:
#Handling Age

df.loc[(df["Age"] < 17) | (df["Age"] > 30), "Age"] = np.nan
df["Age"] = df["Age"].fillna(df["Age"].mean())

Feature Engineering

In [38]:
#Average marks

df["Average_Marks"] = df[["Maths", "Programming", "Communication"]].mean(axis=1)

In [39]:
#Performance category

df["Performance"] = pd.cut(
    df["Average_Marks"],
    bins=[0, 50, 70, 85, 100],
    labels=["Poor", "Average", "Good", "Excellent"]
)

In [40]:
#pass/fail

df["Result"] = np.where(df["Average_Marks"] >= 40, "Pass", "Fail")

In [41]:
df.head()

,Student_ID,Name,Age,Gender,Course,City,CGPA,Maths,Programming,Communication,Date,Average_Marks,Performance,Result
0,1,Aarav Sharma,20.0,Male,BE IT,Pune,8.200000,82,76.0,88.0,2026-01-15,82.000000,Good,Pass
1,2,Priya Patil,21.0,Female,BE IT,Mumbai,9.100000,91,89.0,94.0,2026-01-16,91.333333,Excellent,Pass
2,3,Rohan Kulkarni,20.0,Male,BE IT,Pune,7.400000,74,68.0,72.0,2026-01-17,71.333333,Good,Pass
3,4,Sneha Joshi,22.0,Female,BE IT,Nashik,8.700000,86,92.0,85.0,2026-01-18,87.666667,Excellent,Pass
4,5,Aditya Deshmukh,21.0,Male,BE IT,Pune,7.796875,65,71.0,69.0,2026-01-19,68.333333,Average,Pass

Encoding categorical data

In [42]:
#Label encoding for Gender

df["Gender_Encoded"] = df["Gender"].map({
    "Male": 0,
    "Female": 1
})

In [43]:
#One-hot encoding for City

df = pd.get_dummies(df, columns=["City"], dtype=int)

In [44]:
df.head()

,Student_ID,Name,Age,Gender,Course,CGPA,Maths,Programming,Communication,Date,Average_Marks,Performance,Result,Gender_Encoded,City_Mumbai,City_Nagpur,City_Nashik,City_Pune
0,1,Aarav Sharma,20.0,Male,BE IT,8.200000,82,76.0,88.0,2026-01-15,82.000000,Good,Pass,0,0,0,0,1
1,2,Priya Patil,21.0,Female,BE IT,9.100000,91,89.0,94.0,2026-01-16,91.333333,Excellent,Pass,1,1,0,0,0
2,3,Rohan Kulkarni,20.0,Male,BE IT,7.400000,74,68.0,72.0,2026-01-17,71.333333,Good,Pass,0,0,0,0,1
3,4,Sneha Joshi,22.0,Female,BE IT,8.700000,86,92.0,85.0,2026-01-18,87.666667,Excellent,Pass,1,0,0,1,0
4,5,Aditya Deshmukh,21.0,Male,BE IT,7.796875,65,71.0,69.0,2026-01-19,68.333333,Average,Pass,0,0,0,0,1

Rename columns to lowercase

In [46]:
df.columns = df.columns.str.lower()
df.columns

Index(['student_id', 'name', 'age', 'gender', 'course', 'cgpa', 'maths',
       'programming', 'communication', 'date', 'average_marks', 'performance',
       'result', 'gender_encoded', 'city_mumbai', 'city_nagpur', 'city_nashik',
       'city_pune'],
      dtype='object')

Convert float to integer where applicable

In [48]:
df["age"] = df["age"].round().astype(int)
df["maths"] = df["maths"].round().astype(int)
df["programming"] = df["programming"].round().astype(int)
df["communication"] = df["communication"].round().astype(int)

Final inspection

In [49]:
df.head()

,student_id,name,age,gender,course,cgpa,maths,programming,communication,date,average_marks,performance,result,gender_encoded,city_mumbai,city_nagpur,city_nashik,city_pune
0,1,Aarav Sharma,20,Male,BE IT,8.200000,82,76,88,2026-01-15,82.000000,Good,Pass,0,0,0,0,1
1,2,Priya Patil,21,Female,BE IT,9.100000,91,89,94,2026-01-16,91.333333,Excellent,Pass,1,1,0,0,0
2,3,Rohan Kulkarni,20,Male,BE IT,7.400000,74,68,72,2026-01-17,71.333333,Good,Pass,0,0,0,0,1
3,4,Sneha Joshi,22,Female,BE IT,8.700000,86,92,85,2026-01-18,87.666667,Excellent,Pass,1,0,0,1,0
4,5,Aditya Deshmukh,21,Male,BE IT,7.796875,65,71,69,2026-01-19,68.333333,Average,Pass,0,0,0,0,1

In [50]:
df.shape

(30, 18)

In [51]:
df.dtypes

student_id                 int64
name                      object
age                        int64
gender                    object
course                    object
cgpa                     float64
maths                      int64
programming                int64
communication              int64
date              datetime64[ns]
average_marks            float64
performance             category
result                    object
gender_encoded             int64
city_mumbai                int64
city_nagpur                int64
city_nashik                int64
city_pune                  int64
dtype: object

In [52]:
df.isnull().sum()

student_id        0
name              0
age               0
gender            0
course            0
cgpa              0
maths             0
programming       0
communication     0
date              0
average_marks     0
performance       0
result            0
gender_encoded    0
city_mumbai       0
city_nagpur       0
city_nashik       0
city_pune         0
dtype: int64

In [53]:
df.duplicated().sum()

np.int64(0)

In [55]:
#Saving cleaned dataset

df.to_csv("student_data_cleaned.csv", index=False)

from google.colab import files

files.download("student_data_cleaned.csv")