In [1]:
import pandas as pd

# Sample dataset
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "Gender": ["Female", "Male", "Male"],
    "Salary": [50000, 60000, 70000],
    "Joining_Date": ["2022-01-01", "2021-06-15", "2020-03-20"]
}

df = pd.DataFrame(data)

# Display dataset
df

      Name  Age  Gender  Salary Joining_Date
0    Alice   25  Female   50000   2022-01-01
1      Bob   30    Male   60000   2021-06-15
2  Charlie   35    Male   70000   2020-03-20

In [2]:
# Check data types
df.dtypes

Name            object
Age              int64
Gender          object
Salary           int64
Joining_Date    object
dtype: object

In [3]:
import pandas as pd
import numpy as np

# Sample numerical data
data = {
    "Age": [18, 29, 90, 40, 60],
    "Salary": [20000, 30000, 500000, 80000, 150000]
}

df = pd.DataFrame(data)
df

   Age  Salary
0   18   20000
1   29   30000
2   90  500000
3   40   80000
4   60  150000

In [4]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

df_scaled = df.copy()
df_scaled[["Age", "Salary"]] = scaler.fit_transform(df[["Age", "Salary"]])

df_scaled

        Age    Salary
0 -1.156513 -0.763804
1 -0.723804 -0.707642
2  1.675763  1.931975
3 -0.291095 -0.426832
4  0.495648 -0.033697

In [5]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

df_normalized = df.copy()
df_normalized[["Age", "Salary"]] = scaler.fit_transform(df[["Age", "Salary"]])

df_normalized

        Age    Salary
0  0.000000  0.000000
1  0.152778  0.020833
2  1.000000  1.000000
3  0.305556  0.125000
4  0.583333  0.270833

In [6]:
# Apply log transformation
df_log = df.copy()
df_log["Salary_Log"] = np.log(df_log["Salary"])

df_log

   Age  Salary  Salary_Log
0   18   20000    9.903488
1   29   30000   10.308953
2   90  500000   13.122363
3   40   80000   11.289782
4   60  150000   11.918391

In [7]:
# Create bins for Age
bins = [0, 20, 40, 100]
labels = ["Young", "Adult", "Senior"]

df["Age_Group"] = pd.cut(df["Age"], bins=bins, labels=labels)

df

   Age  Salary Age_Group
0   18   20000     Young
1   29   30000     Adult
2   90  500000    Senior
3   40   80000     Adult
4   60  150000    Senior

In [8]:
import pandas as pd

data = {
    "Name": ["A", "B", "C", "D", "E","F"],
    "Gender": ["Male", "Female", "Female", "Male", "B","Female"],
    "City": ["Mumbai", "Delhi", "Mumbai", "Pune", "Delhi","Delhi"],
    "Performance": ["Low", "Medium", "High", "Medium", "Low","High"]
}

df = pd.DataFrame(data)
df

  Name  Gender    City Performance
0    A    Male  Mumbai         Low
1    B  Female   Delhi      Medium
2    C  Female  Mumbai        High
3    D    Male    Pune      Medium
4    E       B   Delhi         Low
5    F  Female   Delhi        High

In [9]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["Gender_Label"] = le.fit_transform(df["Gender"])
df["City_Label"] = le.fit_transform(df["City"])
df

  Name  Gender    City Performance  Gender_Label  City_Label
0    A    Male  Mumbai         Low             2           1
1    B  Female   Delhi      Medium             1           0
2    C  Female  Mumbai        High             1           1
3    D    Male    Pune      Medium             2           2
4    E       B   Delhi         Low             0           0
5    F  Female   Delhi        High             1           0

In [10]:
# Define order
order = {"Low": 3, "Medium": 2, "High": 1}

df["Performance_Ordinal"] = df["Performance"].map(order)
df

,Name,Gender,City,Performance,Gender_Label,City_Label,Performance_Ordinal
0,A,Male,Mumbai,Low,2,1,3
1,B,Female,Delhi,Medium,1,0,2
2,C,Female,Mumbai,High,1,1,1
3,D,Male,Pune,Medium,2,2,2
4,E,B,Delhi,Low,0,0,3
5,F,Female,Delhi,High,1,0,1

In [11]:
freq = df["City"].value_counts()

df["City_Freq"] = df["City"].map(freq)
df

,Name,Gender,City,Performance,Gender_Label,City_Label,Performance_Ordinal,City_Freq
0,A,Male,Mumbai,Low,2,1,3,2
1,B,Female,Delhi,Medium,1,0,2,3
2,C,Female,Mumbai,High,1,1,1,2
3,D,Male,Pune,Medium,2,2,2,1
4,E,B,Delhi,Low,0,0,3,3
5,F,Female,Delhi,High,1,0,1,3

In [12]:
# Create a dummy target variable
df["Target"] = [0, 1, 1, 0, 1,2]

# Calculate mean target per category
target_mean = df.groupby("City")["Target"].mean()

df["City_Target_Encoded"] = df["City"].map(target_mean)
df

,Name,Gender,City,Performance,Gender_Label,City_Label,Performance_Ordinal,City_Freq,Target,City_Target_Encoded
0,A,Male,Mumbai,Low,2,1,3,2,0,0.500000
1,B,Female,Delhi,Medium,1,0,2,3,1,1.333333
2,C,Female,Mumbai,High,1,1,1,2,1,0.500000
3,D,Male,Pune,Medium,2,2,2,1,0,0.000000
4,E,B,Delhi,Low,0,0,3,3,1,1.333333
5,F,Female,Delhi,High,1,0,1,3,2,1.333333